---
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: Kubernetes Set Context and KUBECONFIG for Service Account (SA)
author: '@vbem'
description: Create K8s context and set KUBECONFIG for service account
branding:
  icon: settings
  color: green

inputs:
  server:
    description: 'K8s cluster server URL'
    required: true    
  ca-base64:
    description: 'K8s cluster Certificate Authority data base64'
    required: true
  cluster:
    description: 'K8s cluster name'
    required: false
    default: ''
  token:
    description: 'Service Account bearer token'
    required: true
  sa:
    description: 'Service Account name'
    required: false
    default: sa
  context:
    description: 'Context name in kubeconfig'
    required: false
    default: ''
  namespace:
    description: 'Context namespace in kubeconfig'
    required: false
    default: ''
  current:
    description: 'Set as current-context in kubeconfig'
    required: false
    default: true
  kubeconfig:
    description: 'Path of kubeconfig file'
    required: false
    default: ''
  export:
    description: 'Set the KUBECONFIG environment variable available to subsequent steps'
    required: false
    default: true
  version:
    description: 'Show client and server version information for the current context'
    required: false
    default: true

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions
outputs:
  context:
    description: 'Context name in kubeconfig'
    value: ${{ steps.main.outputs.context }}
  kubeconfig:
    description: Path of kubeconfig file
    value: ${{ steps.main.outputs.path }}

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
runs:
  using: composite
  steps:
    - id: main
      shell: bash
      run: |
        # implementation details
        
        # Extract host from an URL
        #   $1: URL
        #   stdout: host
        #   $?: 0 if successful and non-zero otherwise
        function kit::str::extractHost {
            local url="$1" # for Parameter Expansion & Pattern Matching
            url="${url/#*:\/\/}"
            url="${url/%:*}"
            echo -n "${url/%\/*}"
        }
        
        # Group stdin to stderr with title
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines
        #   $1: group title
        #   stdin: logs
        #   stderr: grouped logs
        #   $?: 0 if successful and non-zero otherwise
        function kit::wf::group {
            echo "::group::$1"      >&2
            echo "$(< /dev/stdin)"  >&2
            echo '::endgroup::'     >&2
        }
        
        # Set stdin as value to environment with given name
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        #   $1: environment variable name
        #   stdin: environment variable value
        #   stderr: grouped logs
        #   $?: 0 if successful and non-zero otherwise
        function kit::wf::env {
            local val
            val="$(< /dev/stdin)"
            echo "$1<<__GITHUB_ENV__"   >> "$GITHUB_ENV"
            echo "$val"                 >> "$GITHUB_ENV"
            echo '__GITHUB_ENV__'       >> "$GITHUB_ENV"
            kit::wf::group "💲 append '$1' to \$GITHUB_ENV" <<< "$val"
        }
        
        # Set stdin as value to output of current step with given name
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
        # https://renehernandez.io/snippets/multiline-strings-as-a-job-output-in-github-actions/
        #   $1: output name
        #   stdin: output value
        #   stderr: grouped logs
        #   $?: 0 if successful and non-zero otherwise
        function kit::wf::output {
            local val
            val="$(< /dev/stdin)"
            echo "::set-output name=$1::$val" >&2
            kit::wf::group "📤 set '$1' to step outputs" <<< "$val"
        }
        
        SERVER='${{ inputs.server }}'
        CA_BASE64='${{ inputs.ca-base64 }}'
        [[ -n '${{ inputs.cluster }}' ]] && CLUSTER='${{ inputs.cluster }}' || CLUSTER="$(kit::str::extractHost '${{ inputs.server }}')"
        TOKEN='${{ inputs.token }}'
        SA='${{ inputs.sa }}'
        [[ -n '${{ inputs.context }}' ]] && CONTEXT='${{ inputs.context }}' || CONTEXT="${{ inputs.sa }}.$CLUSTER"
        NAMESPACE='${{ inputs.namespace }}'
        CURRENT='${{ inputs.current }}'
        [[ -n '${{ inputs.kubeconfig }}' ]] && KUBECONFIG='${{ inputs.kubeconfig }}' || KUBECONFIG="${{ runner.temp }}/$CONTEXT.kubeconfig"
        EXPORT='${{ inputs.export }}'
        VERSION='${{ inputs.version }}'
        
        kit::wf::group '📥 action inputs' << __HEREDOC__
        server:     $SERVER
        cluster:    $CLUSTER
        sa:         $SA
        context:    $CONTEXT
        namespace:  $NAMESPACE
        current:    $CURRENT
        kubeconfig: $KUBECONFIG
        export:     $EXPORT
        version:    $VERSION
        __HEREDOC__
        
        declare -rx KUBECONFIG
        {
          kubectl config set-cluster "$CLUSTER" --server="$SERVER" >&1
          kubectl config set "clusters.$CLUSTER.certificate-authority-data" "$CA_BASE64" >&1
          kubectl config set-credentials "$SA" --token="$TOKEN" >&1
          kubectl config set-context "$CONTEXT" --cluster="$CLUSTER" --user="$SA" --namespace="$NAMESPACE" >&1
          [[ "$CURRENT" == 'true' ]] && kubectl config use-context "$CONTEXT" >&1
        } | kit::wf::group '🚢 kubectl config set'
        
        kubectl config view --raw=false | yq -Ce | kit::wf::group '🚢 kubectl config view'
        
        kit::wf::output 'kubeconfig' <<< "$KUBECONFIG"
        
        [[ "$EXPORT" == 'true' ]] && kit::wf::env 'KUBECONFIG' <<< "$KUBECONFIG"
        
        [[ "$VERSION" == 'true' ]] && kubectl version -o yaml | yq -Ce | kit::wf::group '🚢 kubectl version'
...